### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [7]:
import numpy as np

vector = np.random.rand(10)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("Vector:")
print(vector)
print("Vector shape:", vector.shape)

print("Matrix:")
print(matrix)
print("Matrix shape:", matrix.shape)


Vector:
[0.80288226 0.51964015 0.90376099 0.48572084 0.32849236 0.22158476
 0.06076206 0.45715537 0.75250895 0.57079629]
Vector shape: (10,)
Matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [8]:
vector_plus_10 = np.round(vector + 10, 2)
matrix_multiplied = matrix * 2
vector_squared = vector ** 2

print("Vector + 10 rounded to 2 decimals:")
print(vector_plus_10)

print("Matrix multiplied by 2:")
print(matrix_multiplied)

print("Vector squared:")
print(vector_squared)


Vector + 10 rounded to 2 decimals:
[10.8  10.52 10.9  10.49 10.33 10.22 10.06 10.46 10.75 10.57]
Matrix multiplied by 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]
Vector squared:
[0.64461993 0.27002589 0.81678393 0.23592474 0.10790723 0.0490998
 0.00369203 0.20899103 0.56626972 0.3258084 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0, 1], [1, 0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [10]:
result_matrix = B @ A
result_vector = result_matrix @ C
result_matrix_D = result_matrix @ D

print("Result matrix:")
print(result_matrix)

print("Result matrix multiplied by C:")
print(result_vector)

print("Result matrix multiplied by D:")
print(result_matrix_D)

Result matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]
Result matrix multiplied by C:
[[0.5202]
 [0.2846]]
Result matrix multiplied by D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
result_matrix_transposed = result_matrix.T

print("Transposed result_matrix:")
print(result_matrix_transposed)
print("Shape:", result_matrix_transposed.shape)

vector_transposed = vector.T

print("\nTransposed vector:")
print(vector_transposed)
print("Original vector shape:", vector.shape)
print("Transposed vector shape:", vector_transposed.shape)

column_vector = np.expand_dims(vector, axis=1)

print("\nOriginal vector:")
print(vector)
print("Original vector shape:", vector.shape)

print("\nColumn vector:")
print(column_vector)
print("Column vector shape:", column_vector.shape)

column_vector_transposed = column_vector.T

print("\nTransposed column_vector:")
print(column_vector_transposed)
print("Transposed column_vector shape:", column_vector_transposed.shape)


Transposed result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]
Shape: (2, 2)

Transposed vector:
[0.80288226 0.51964015 0.90376099 0.48572084 0.32849236 0.22158476
 0.06076206 0.45715537 0.75250895 0.57079629]
Original vector shape: (10,)
Transposed vector shape: (10,)

Original vector:
[0.80288226 0.51964015 0.90376099 0.48572084 0.32849236 0.22158476
 0.06076206 0.45715537 0.75250895 0.57079629]
Original vector shape: (10,)

Column vector:
[[0.80288226]
 [0.51964015]
 [0.90376099]
 [0.48572084]
 [0.32849236]
 [0.22158476]
 [0.06076206]
 [0.45715537]
 [0.75250895]
 [0.57079629]]
Column vector shape: (10, 1)

Transposed column_vector:
[[0.80288226 0.51964015 0.90376099 0.48572084 0.32849236 0.22158476
  0.06076206 0.45715537 0.75250895 0.57079629]]
Transposed column_vector shape: (1, 10)
